FitnessTracker/meals/urls.py
from django.urls import path, include

from FitnessTracker.meals.views import MealsDashboardView, MealCreateView, MealEditView, MealDeleteView

urlpatterns = [
    path('dashboard/', MealsDashboardView.as_view(), name='meals-dashboard'),
    path('create/', MealCreateView.as_view(), name='create-meal'),
    path('<int:pk>/', include([
        path('edit/', MealEditView.as_view(), name='edit-meal'),
        path('remove/', MealDeleteView.as_view(), name='remove-meal')
    ])),
]

FitnessTracker/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from FitnessTracker import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('FitnessTracker.common.urls')),
    path('workouts/', include('FitnessTracker.workouts.urls')),
    path('accounts/', include('FitnessTracker.accounts.urls')),
    path('meals/', include('FitnessTracker.meals.urls')),
    path('progress/', include('FitnessTracker.progress.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FitnessTracker/meals/models.py
from django.conf import settings
from django.db import models


# Create your models here.
class Meal(models.Model):
    class Meta:
        ordering = ['-created_at']

    name = models.CharField(
        max_length=255
    )

    calories = models.PositiveIntegerField(
        default=0,
        null=True,
        blank=True
    )

    ingredients = models.TextField(
        null=True,
        blank=True
    )

    additional_notes = models.TextField(
        null=True,
        blank=True
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    updated_at = models.DateTimeField(
        auto_now=True
    )

    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='meals',
    )

    def __str__(self):
        return self.name

FitnessTracker/meals/forms.py
from django import forms
from django.forms import TextInput, NumberInput, Textarea

from FitnessTracker.meals.models import Meal


class MealBaseForm(forms.ModelForm):
    class Meta:
        model = Meal
        exclude = ('created_at', 'updated_at', 'user')

        widgets = {
            'name': TextInput(
                attrs={
                    'placeholder': 'Enter meal name'
                }
            ),
            'calories': NumberInput(
                attrs={
                    'placeholder': 'Enter calorie count'
                }
            ),
            'ingredients': Textarea(
                attrs={
                    'placeholder': 'Enter the ingredients. Ex: ing1, ing2, ing3...',
                    'rows': 3
                }
            ),
            'additional_notes': Textarea(
                attrs={
                    'placeholder': 'Add any notes or comments about the meal',
                    'rows': 3
                }
            )
        }

        labels = {
            'name': 'Meal Name',
            'calories': 'Calories (kcal)',
            'ingredients': 'Ingredients',
            'additional_notes': 'Additional Notes (Optional)'
        }


class MealCreateForm(MealBaseForm):
    pass


class MealEditForm(MealBaseForm):
    pass

FitnessTracker/meals/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView

from FitnessTracker.meals.forms import MealCreateForm, MealEditForm
from FitnessTracker.meals.models import Meal


# Create your views here.
class MealsDashboardView(LoginRequiredMixin, ListView):
    model = Meal
    template_name = 'meals/meals-dashboard.html'

    def get_queryset(self):
        return Meal.objects.filter(user=self.request.user)


class MealCreateView(LoginRequiredMixin, CreateView):
    model = Meal
    form_class = MealCreateForm
    template_name = 'meals/add-meal.html'
    success_url = reverse_lazy('meals-dashboard')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class MealEditView(LoginRequiredMixin, UpdateView):
    model = Meal
    form_class = MealEditForm
    template_name = 'meals/edit-meal.html'
    success_url = reverse_lazy('meals-dashboard')

    def dispatch(self, request, *args, **kwargs):
        meal = get_object_or_404(Meal, pk=self.kwargs['pk'])

        if meal.user != request.user:
            return HttpResponseRedirect(reverse('homepage'))

        return super().dispatch(request, *args, **kwargs)


class MealDeleteView(LoginRequiredMixin, DeleteView):
    model = Meal
    template_name = 'meals/remove-meal.html'
    success_url = reverse_lazy('meals-dashboard')

    def dispatch(self, request, *args, **kwargs):
        meal = get_object_or_404(Meal, pk=self.kwargs['pk'])

        if meal.user != request.user:
            return HttpResponseRedirect(reverse('homepage'))

        return super().dispatch(request, *args, **kwargs)

templates/meals/add-meal.html
{% extends 'base.html' %}
{% block content %}
    <section class="add-meal-section">
        <div class="container">
            <h2>Add a New Meal</h2>
            <form method="POST">
                {% csrf_token %}

                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <div class="error">{{ field.errors }}</div>
                    </div>
                {% endfor %}

                <!-- Submit Button -->
                <button type="submit" class="btn-submit">Add Meal</button>
            </form>
            <div class="back-to-meals">
                <a href="#" onclick="goBack()" class="btn-back">Back to Meals</a>
            </div>
        </div>
    </section>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock %}

templates/meals/edit-meal.html
{% extends 'base.html' %}

{% block content %}
    <main class="profile-main">
        <section class="edit-meal-section">
            <div class="container">
                <h2>Edit Meal</h2>
                <form action="#" method="POST">
                    <!-- CSRF Token -->
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">Update Meal</button>
                </form>
            </div>
        </section>
    </main>

{% endblock %}

templates/meals/meals-dashboard.html
{% extends 'base.html' %}
{% block content %}
    <section class="meals-section">
        <div class="container">
            <h2>Your Meals</h2>
            <div class="add-meal">
                <a href="{% url 'create-meal' %}" class="btn-add-meal">Add New Meal</a>
            </div>
            <div class="meals-list">
                {% if not meal_list %}
                    <h2>No meals.</h2>
                {% else %}
                    {% for meal in meal_list %}
                        <div class="meal-card">
                            <h3>{{ meal.name }}</h3>
                            <p>Calories: {{ meal.calories }} kcal</p>
                            <p>Ingredients: {{ meal.ingredients }}</p>
                            <p>Additional notes: {{ meal.additional_notes }}</p>
                            {% load tz %}
                            {% localtime %}
                                <p>Created
                                    At: {{ meal.created_at|date:"M d, Y" }}</p>
                            {% endlocaltime %}
                            {% localtime %}
                                <p>Last
                                    Updated: {{ meal.updated_at|date:"M d, Y" }}</p>
                            {% endlocaltime %}

                            <div class="meal-actions">
                                <a href="{% url 'edit-meal' meal.pk %}" class="btn-edit">Edit</a>
                                <a href="{% url 'remove-meal' meal.pk %}" class="btn-remove">Remove</a>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
                <!-- Repeat Meal Cards -->
            </div>
        </div>
    </section>
{% endblock %}

templates/meals/remove-meal.html
{% extends 'base.html' %}

{% block content %}
    <main class="profile-main">
        <section class="remove-meal-section">
            <div class="container">
                <h2>Are you sure you want to remove this meal: {{ meal.name }}?</h2>

                <div class="action-buttons">
                    <a href="{% url 'meals-dashboard' %}" class="btn btn-cancel">Cancel</a>
                    <form action="{% url 'remove-meal' meal.pk %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-remove">Remove</button>
                    </form>
                </div>
            </div>
        </section>
    </main>
{% endblock %}